name: Deploy to EC2 Hml
on:
  # schedule:
  #   - cron: '00 22 * * 1-5'
  workflow_dispatch:
  # push: 
  #   branches: [master, staging]
  # pull_request: 
  #   branches: [master, staging]

env:
  DOCKER_TAG: latest
  AWS_REGION: ${{ secrets.AWS_REGION }}}
  ECR_REGISTRY: ${{ secrets.ECR_REGISTRY}}
  ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
  INSTANCE_TAG: ${{ secrets.INSTANCE_TAG }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:

  
    - name: Checkout
      id: checkout
      uses: actions/checkout@v2
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Configure AWS credentials
      id: aws-credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      
    - name: Build and push Docker image
      env:
        IMAGE_TAG: latest
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile
        platforms: linux/arm64
        push: true
        tags: ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:latest
        build-args: |
          DATABASE_URL=${{ secrets.DATABASE_URL }}
        cache-from: | 
          type=gha
        cache-to: | 
          type=gha,mode=max  
 
