name: Migrate Dev
on:
  # schedule:
  #   - cron: '00 22 * * 1-5'
  workflow_dispatch:
  # push: 
  #   branches: [master, staging]
  # pull_request: 
  #   branches: [master, staging]

env:
  DOCKER_TAG: latest
  AWS_REGION: ${{ secrets.AWS_REGION }}}
  ECR_REGISTRY: ${{ secrets.ECR_REGISTRY}}
  ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
  INSTANCE_TAG: ${{ secrets.INSTANCE_TAG }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:

    - name: Configure AWS credentials
      id: aws-credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1


    - name: Session Manager
      id: ssm-into-ec2
      run: |-
        sudo usermod -aG docker $USER
        aws ssm send-command \
          --document-name "AWS-RunShellScript" \
          --targets Key=tag:aws:autoscaling:groupName,Values=$INSTANCE_TAG \
          --parameters commands=["echo `128596` | su -c docker exec container_name sh -c `touch /var/log/teste-file.txt`" $USER]
          
          # ["docker exec container_name sh -c `touch /var/log/teste-file.txt`"] 
   
# docker exec container_name sh -c 'touch /var/log/teste-file.txt'
# echo `128596` | su -c "docker exec container_name sh -c `touch /var/log/teste-file.txt`" $USER
